# Generated by Django 4.0.1 on 2022-04-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_bhavcopy_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equitysec',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
