# Generated by Django 4.0.1 on 2022-04-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhavcopy',
            old_name='company',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='equitysec',
            old_name='company',
            new_name='symbol',
        ),
    ]
