# Generated by Django 4.0.1 on 2022-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_company_bhavcopy_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopy',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equitysec',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
