# Generated by Django 4.0.1 on 2022-04-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_bhavcopy_symbol_alter_equitysec_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopy',
            name='timeStamp',
            field=models.CharField(max_length=15),
        ),
    ]
